version: "3.9"

services:
  app:
    build: .
    container_name: auto-wa
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./auth:/app/auth
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Jakarta

  redis:
    image: redis:7
    container_name: redis
    restart: always
